name: Browser Bug Report
description: Report a bug in the browser client
title: "[Browser Bug]: "
labels: ["bug", "browser"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to the page...
        2. Click on '...'
        3. See error
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 22.04
          - **Browser**: Chrome 115
          - **App**: 1.0.0
      value: |
          - OS:
          - Browser:
          - App:
      render: markdown
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
