name: preview

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.mdx'
      - 'docs/**'
      - '**/docs/**'

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build ClearSky API package
        run: npm --workspace clearsky-api run build

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        env:
          APP_VARIANT: preview
        with:
          command: eas update --auto
          working-directory: apps/akari

      - name: Export preview web bundle
        working-directory: apps/akari
        env:
          APP_VARIANT: preview
        run: |
          set -euo pipefail
          npm run build:preview -- --platform web --output-dir dist/web

      - name: Deploy preview web bundle to Expo Hosting
        working-directory: apps/akari
        env:
          APP_VARIANT: preview
          EXPO_CLI_NO_PROMPT: 1
          EXPO_NO_TELEMETRY: 1
        run: |
          set -euo pipefail
          eas deploy --environment preview --alias pr-${{ github.event.pull_request.number }} --export-dir dist/web --non-interactive
