name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  production-build:
    name: EAS Production Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            echo "Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build ClearSky API package
        run: npm --workspace clearsky-api run build

      - name: Run production build
        working-directory: apps/akari
        run: |
          set -o pipefail
          eas build --profile production --platform all --non-interactive --wait --json | tee production-build-result.json

      - name: Upload build manifest
        uses: actions/upload-artifact@v4
        with:
          name: eas-production-build
          path: apps/akari/production-build-result.json

      - name: Summarize build results
        run: |
          {
            echo "### EAS Production Build"
            echo
            echo '```json'
            cat apps/akari/production-build-result.json
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
