name: test

on:
  pull_request:
    paths:
      - 'apps/akari/**'
      - '.github/workflows/test.yml'

jobs:
  coverage:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: apps/akari
          test-script: npm run test:coverage
