name: test

on:
  pull_request:

jobs:
  coverage:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test:coverage --workspaces --if-present
      - name: Merge coverage reports
        run: mkdir -p coverage && rm -f coverage/lcov.info && npx --yes lcov-result-merger "**/coverage/lcov.info" coverage/lcov.info --ignore "node_modules/**"
      - name: Report coverage
        uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ github.token }}
          lcov-file: coverage/lcov.info
          name: akari-monorepo
          update-comment: true
