name: test

on:
  pull_request:

jobs:
  coverage:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci --workspace=apps/akari
      - run: npm --prefix apps/akari run test:coverage
      - name: Report coverage
        uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ github.token }}
          lcov-file: apps/akari/coverage/lcov.info
          name: apps/akari
          update-comment: true
